[parity]
chain = "./data/spec.json"
base_path = "data/node6"

[network]
port = 30306
discovery = true
bootnodes = ["enode://c3a7ba87ac7030f3ca33b3a863b01f9b1fd1f9c9993138c6a6848e8fb081b8f69fd853edc0e7d3432b9d4f9ea4e2ed9dc0c96c8467c7a7c35329d97cd6eb1527@127.0.0.1:30300","enode://184576eda877a9abe03e4092aa91e7ff801311deb54f09a64d451a3d1ff3a9acd4a48bdac2a16d62685901f347546f1542b9f3ae891c97b355ae18138d618793@127.0.0.1:30301","enode://58287ec086938c118e147902452a9efa64185fa82eda4cf44d24dbdee24afaf0c534b5d8cf9509c7be80ea3c1bd50c015bbd2a08c091b0f4274b3c8b229b3a58@127.0.0.1:30302","enode://10d45c0ec3adf9e6647f5b9e3aa5d0ac1294b171647b7b52cda54882368623f77065e269d6558e8d86a1cb13f1b55860bb39d4b0c7de69a61e2360475c2704cb@127.0.0.1:30303","enode://75bd6f09bbfe59dc751575d4e39634706fc50e0ccd0b9063432770709fa36de9ff2e12363556247c9215658fc3ad6045e11c153ad32f6f6d3867c71dc291cb96@127.0.0.1:30304","enode://69927fe9fcfc27bd28b50a87780baac30e1dacee00ed59d24a044a8578623cf265097df80265fd0b7e9a4555466f1388115d2cf18e6ac16e00a8bd54820247e4@127.0.0.1:30305"]
nat = "none"
interface = "local"

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "personal", "traces"]
port = 8546

[websockets]
port = 9546

[ipc]
disable = true

[secretstore]
disable = true

[account]
unlock = ["0x720e118ab1006cc97ed2ef6b4b49ac04bb3aa6d9"]
password = ["config/password"]

[mining]
force_sealing = true
min_gas_price = 1000000000
gas_floor_target = "12000000"
engine_signer = "0x720e118ab1006cc97ed2ef6b4b49ac04bb3aa6d9"
reseal_on_txs = "none"
extra_data = "Parity"
tx_gas_limit="7500000"
tx_time_limit=1000

[misc]
logging = "engine=trace,miner=trace,reward=trace"
