[parity]
chain = "./data/spec.json"
base_path = "data/node3"

[network]
port = 30303
discovery = true
bootnodes = ["enode://c3a7ba87ac7030f3ca33b3a863b01f9b1fd1f9c9993138c6a6848e8fb081b8f69fd853edc0e7d3432b9d4f9ea4e2ed9dc0c96c8467c7a7c35329d97cd6eb1527@127.0.0.1:30300","enode://184576eda877a9abe03e4092aa91e7ff801311deb54f09a64d451a3d1ff3a9acd4a48bdac2a16d62685901f347546f1542b9f3ae891c97b355ae18138d618793@127.0.0.1:30301","enode://58287ec086938c118e147902452a9efa64185fa82eda4cf44d24dbdee24afaf0c534b5d8cf9509c7be80ea3c1bd50c015bbd2a08c091b0f4274b3c8b229b3a58@127.0.0.1:30302"]
nat = "none"
interface = "local"

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "personal", "traces"]
port = 8543

[websockets]
port = 9543

[ipc]
disable = true

[secretstore]
disable = true

[account]
unlock = ["0x522df396ae70a058bd69778408630fdb023389b2"]
password = ["config/password"]

[mining]
force_sealing = true
min_gas_price = 1000000000
gas_floor_target = "12000000"
engine_signer = "0x522df396ae70a058bd69778408630fdb023389b2"
reseal_on_txs = "none"
extra_data = "Parity"
tx_gas_limit="7500000"
tx_time_limit=1000

[misc]
logging = "engine=trace,miner=trace,reward=trace"
